import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "wearly.",
  description: "Generated by create next app",
};

export default function FrontLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className="flex-grow container mx-auto px-4">{children}</main>;
}
